import { PaymentProvider } from '../types/payment';

export const paymentProviders: PaymentProvider[] = [
  {
    id: 'orange-money',
    name: 'Orange Money',
    logo: '/images/payments/orange-money.svg',
    description: 'Payez facilement avec votre compte Orange Money',
    fees: 1.5,
    minAmount: 100,
    maxAmount: 1000000,
    processingTime: 'Instantané',
  },
  {
    id: 'wave',
    name: 'Wave',
    logo: '/images/payments/wave.svg',
    description: 'Transfert d\'argent rapide avec Wave',
    fees: 1,
    minAmount: 100,
    maxAmount: 1000000,
    processingTime: 'Instantané',
  },
  {
    id: 'free-money',
    name: 'Free Money',
    logo: '/images/payments/free-money.svg',
    description: 'Paiement sécurisé via Free Money',
    fees: 1.5,
    minAmount: 100,
    maxAmount: 500000,
    processingTime: 'Instantané',
  },
  {
    id: 'bank-transfer',
    name: 'Virement bancaire',
    logo: '/images/payments/bank-transfer.svg',
    description: 'Payez par virement bancaire',
    fees: 0,
    minAmount: 1000,
    maxAmount: 10000000,
    processingTime: '24-48h',
  },
  {
    id: 'cash-on-delivery',
    name: 'Paiement à la livraison',
    logo: '/images/payments/cash.svg',
    description: 'Payez en espèces à la livraison',
    fees: 0,
    minAmount: 0,
    maxAmount: 500000,
    processingTime: 'À la livraison',
  },
];